# permissions for end users to edit backupscheduleds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backupscheduled-editor-role
rules:
- apiGroups:
  - extension.shepherd
  resources:
  - backupscheduleds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extension.shepherd
  resources:
  - backupscheduleds/status
  verbs:
  - get
