package v1

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduledStatus) DeepCopyInto(out *ScheduledStatus) {}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduledStatus.
func (in *ScheduledStatus) DeepCopy() *ScheduledStatus {
	if in == nil {
		return nil
	}
	out := new(ScheduledStatus)
	in.DeepCopyInto(out)
	return out
}
