name: Lint

on:
  push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17'
      - run: |
          go vet ./...
          go install golang.org/x/lint/golint
          golint -set_exit_status `go list ./... | grep -v /vendor/`